[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "fastapi>=0.115.12",
    "google-genai>=1.13.0",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.2",
]
