[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "art>=6.5",
    "black>=25.1.0",
    "colorama>=0.4.6",
    "google-genai>=1.13.0",
    "openai>=1.76.2",
    "pillow>=11.2.1",
    "pyfiglet>=1.0.2",
    "python-dotenv>=1.1.0",
    "rich>=14.0.0",
    "uvicorn>=0.34.2",
    "yaspin>=3.1.0",
]
